name: ToxTest

on:
  pull_request:

  workflow_dispatch:

jobs:
  run_tox:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.8,3.9,3.10.x]
        rbf_version: [5.0.1,6.0]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions poetry robotframework==${{ matrix.rbf_version }}

      - name: test with tox
        run: tox

      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Acceptance Tests
          path: TEST_*.xml
          reporter: xunit-junit

