name: ToxTest

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions poetry
          pip install genbadge[all]

      - name: test with tox
        run: tox
